_BASE_: ../../maskformer_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SEM_SEG_HEAD:
    PIXEL_DECODER_NAME: "LawinTransformerPixelDecoder"
    NAME: "MaskFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 150
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256 # not used 
    MASK_DIM: 256 # not used
    NORM: "GN"
    SHORT_CUT: True
    NHEADS: 16
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "swin_tiny_patch4_window7_224.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  BASE_LR: 0.00006
  WARMUP_FACTOR: 1e-6
  WARMUP_ITERS: 1500
  WEIGHT_DECAY: 0.01
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0
  BACKBONE_MULTIPLIER: 1.0
